FROM python:3.12-slim
ARG SJP_TAG="main"
ADD https://github.com/MrDave/StaticJinjaPlus.git#${SJP_TAG} /opt/StaticJinjaPlus

WORKDIR /opt/StaticJinjaPlus
RUN python3 -m venv venv && \
    venv/bin/pip install -r requirements.txt --no-cache-dir

ENTRYPOINT ["venv/bin/python", "main.py"]
CMD ["--srcpath=src/templates/", "--outpath=src/build/"]